canonical/k8s-dqlite

- go.mod
- go.sum
- vendor/modules.txt
The `kine` dependency is pointing to a local directory that does not exist on others.
> fix kine dependency

- README.md
- go.mod
- go.sum
- vendor/modules.txt
The PR adds instructions on how to setup a Highly available Dqlite backend.
> Instructions on how to setup HA dqlite

- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/stale.yml
- .github/workflows/build-snap.yml
Just build the snap and run a range test from etcd
> Add GH action

- snap/snapcraft.yaml
Update the dqlite build process with the lz4 suport
> Use the new lz4 build

- go.mod
Things like getting the leader did not work. This PR fixes this.
> Update to the latest go-dqlite

- app/app.go
- app/options/options.go
- server/server.go
Add command-line arguments for optionally enabling debug pprof endpoints for k8s-dqlite
> Add command-line flags for enabling pprof endpoint

- README.md
Closes #26 
Update readme build instructions with required `CGO_LDFLAGS_ALLOW` flag.
> Mention required CGO_LDFLAGS_ALLOW build flag

- go.mod
- go.sum
To be merged after https://github.com/canonical/kine/pull/9
> Update to kine 0.4.1-k8s-dqlite.4

- go.mod
- go.sum
Update kine to include https://github.com/canonical/kine/pull/11
> Bump kine to 0.4.1-k8s-dqlite.5

- README.md
Document steps to setup a development environment of k8s-dqlite and kine against a running MicroK8s instance.
cc @solmyrcan
> document local hacking dev environment with microk8s

- cmd/root.go
- pkg/server/server.go
Add --min-tls-version flag to k8s-dqlite
> Add --min-tls-version flag for dqlite endpoint

- cmd/root.go
- pkg/kine/drivers/generic/admission.go
- pkg/kine/drivers/generic/admission_test.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/generic/metrics.go
Integrates the internal metrics of the `limit` policy with Prometheus
> Add LimitPolicy metrics to Prometheus

- .github/workflows/cla-check.yml
> Added CLA check workflow

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/server/list.go
- pkg/kine/server/types.go
> Changes for v1.29 conformance

- README.md
update instructions to build and develop k8s-dqlite
> Update build and test instructions on README

- .github/workflows/trivy.yaml
Adds missing permissions for the trivy Github Action and pins the version.
> Add write permissions for trivy

- pkg/kine/drivers/generic/generic.go
- pkg/kine/prepared/db.go
Add otel traces to the calls to the DB.
> Instrument calls to DB

- .github/.jira_sync_config.yaml
- .github/workflows/scorecard.yaml
- README.md
Scorecard performs numerous checks to ensure that the project follows security best practices. We're adding a badge to the project readme, which shows the current score and includes various suggestions.
At the same time, we're configuring an automated job that will create Jira issues for each Github issue.
> Add scorescard action and jira sync configuration

- .github/workflows/trivy.yaml
Addresses https://github.com/canonical/k8s-dqlite/security/code-scanning/128
Added to level permissions to address the security alert.
> workflows: Add top level permissions to address security alert

- .github/workflows/k8s-snap-integration.yaml
- .github/workflows/performance.yaml
- pkg/kine/logstructured/sqllog/sql.go
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
> back-port: [v1.3] Fix memory leak watch context cancel (#240)

- .github/workflows/cla-check.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yaml
- .github/workflows/trivy.yaml
This PR adds some Github Actions token permission fine tuning to adhere to security best practices.
> chore: make token permissions compatible with POLP

- test/performance/parse-performance-metrics.R
- test/performance/tests/test_util/metrics.py
This PR uses fixed scale for performance test line graphs to improve comparability.
Add an RSS (ResidentSet Size) plot to the existing plots.
Add retry for the kube-burner download
> CI: performance test improvements (RSS plot, fixed scale, retry kube-burner download)

- cmd/migrator.go
- cmd/root.go
- cmd/tracing.go
- pkg/backend/dqlite/driver.go
- pkg/backend/internal/backend/backend.go
- pkg/backend/internal/backend/ttl.go
- pkg/backend/internal/backend/watcher.go
- pkg/backend/sqlite/driver.go
- pkg/client/client.go
- pkg/endpoint/endpoint.go
- pkg/limited/limited.go
- pkg/limited/otel.go
- pkg/limited/watch.go
- pkg/migrator/migrator.go
- pkg/migrator/util.go
- pkg/server/server.go
- pkg/server/util.go
This PR suggests some changes based on the following assumptions about errors:
1) Handle the error if possible 
2) If not, add more context if present and propagate if possible
3) If not, log the error
The log messages are allowed to have Uppercase letters and the lowercase restriction is only applied to error messages.
> refactor: streamline errors

- pkg/backend/dqlite/driver.go
Removes the legacy migration code from the dqlite driver. The migration used to extract data from a sqlite database and instill it into the `kine` table.
> chore: remove dqlite legacy migration

- .github/workflows/k8s-snap-integration.yaml
- .github/workflows/performance.yaml
Backport of https://github.com/canonical/k8s-dqlite/pull/301
> backport: v1.3 CI fix dqlite
