- go.mod
- go.sum
Update Kine version to `v0.4.1-k8s-dqlite.2`, to include https://github.com/canonical/kine/pull/7
Only merge after https://github.com/canonical/kine/pull/7.
> Update kine version

- .github/workflows/build-snap.yml
- app/app.go
- app/options/options.go
- go.mod
- go.sum
- server/server.go
Add experimental disk-mode flag for k8s-dqlite service. Requires bumping the dqlite version on the microk8s snap as well.
> Add --disk-mode command-line argument

- go.mod
- go.sum
> bump go-dqlite to 1.11.7

- app/app.go
- app/options/options.go
- server/server.go
Make the ClientSessionCache configurable in the used TLS dial configuration. Setting a positive size should improve performance with TLS session resumption, but comes at the cost of being incompatible with previous go-dqlite versions.
- (nodeA) Install MicroK8s on 1.26/stable
- (nodeB) Install MicroK8s on latest/edge with this build and --tls-client-session-cache-size=256
- Join nodeB to nodeA. The join process stalls, from the logs we observe that dqlite cannot communicate
- Remove the `--tls-client-session-cache-size` from nodeB, using the default size 0
- Join completes without issues
> TLS dial ClientSessionCache size configuration

- pkg/kine/drivers/generic/generic.go
Reduce CPU busywork when retrying SQL queries. Previously, we would do lots of string operations on each loop, causing a lot of unnecessary memory and CPU ops.
The `Stripped` function is defined here https://github.com/canonical/k8s-dqlite/blob/77616f286e340f6dd76a04d953fcb4b3ee19ab63/pkg/kine/drivers/generic/generic.go#L88-L93, which is multiple string replace, plus a regex compilation and invocation.
> reduce cpu busywork when retrying failed queries

- cmd/root.go
- go.mod
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/generic/metrics.go
Replaces #52
- record a counter for successful/failed transactions and operations by tx_name and result
- record latency for database operations by tx_name and result
- remove unused functions
- add --metrics and --metrics-listen flags in k8s-dqlite command to expose metrics endpoint
- go mod tidy
> Add metrics for operations and individual transactions

- cmd/migrator.go
- cmd/root.go
- pkg/kine/client/client.go
- pkg/migrator/migrator.go
- pkg/migrator/util.go
Replaces #53.
Build go-migrator as a sub-command of k8s-dqlite. Results in a reduced snap size and less binaries to build/bundle.
> Make go-migrator a sub-command of k8s-dqlite

- cmd/root.go
- pkg/server/server.go
- pkg/server/util.go
This would be a starting point to handle full disk cases. The conditions can checked by a watcher which will try to gracefully handover leadership/voter rights and shutdown. The syscall for `unix.Statfs` is really fast, so this check can be handled on queries that would put data to the disk such as `CREATE`,`UPDATE` and `DELETE`.  If having a watcher seems to be the better idea, this work can be finalized by cleaning up some of the ugly code.
> Added full disk watcher and startup condition

- pkg/kine/drivers/generic/admission.go
- pkg/kine/drivers/generic/admission_test.go
- pkg/kine/drivers/generic/generic.go
- test/admission_test.go
- test/mixed_workload_test.go
This PR adds a way to fail requests early based on admission policies which reduces the load on the database.
The following policies are currently available:
* `allow-all`: Disables admission control
* `limit`: Denies queries if maximum amount of Txn is reached.
Closes MK-1302
> Add admission control

- cmd/root.go
- pkg/kine/drivers/generic/admission.go
- pkg/kine/drivers/generic/admission_test.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/server/server.go
- test/admission_test.go
If this flag is enabled, the admission control will only perform checks on write queries. Read queries will be ignored.
> Add `--admission-control-only-write-queries` flag

- pkg/kine/drivers/sqlite/sqlite.go
In #69 the options parsing was moved from dqlite.go to sqlite.go. However, the dataSourceName with the query parameters was wrongly passed to the `generic.Open` call instead of the parsed `opts.dsn` that removed the query parameters.
> Fix wrong parameter for sqlite

- pkg/kine/drivers/generic/generic.go
- test/update_test.go
Solves [https://github.com/canonical/k8s-dqlite/issues/82](https://github.com/canonical/k8s-dqlite/issues/82)
Adds test to expose slowness of list query (https://github.com/canonical/k8s-dqlite/issues/82)
Original list query had maybe quadratic complexity [(plot)](https://www.wolframalpha.com/input?i=quadratic+fit+calculator&assumption=%7B%22F%22%2C+%22QuadraticFitCalculator%22%2C+%22data%22%7D+-%3E%22%7B2551219%2C4238600%2C6427871%2C9495735%2C14600343%2C18155273%2C24599527%2C29835900%2C38340280%2C48312167%2C56213177%2C67317845%2C69894101%2C88913819%2C102723989%2C142948612%2C124230579%2C143282009%2C169605043%7D%22) in terms of number of rows with same name.
New query passes the test, it  still has [superlinear](https://www.wolframalpha.com/input?i=linear+fit+calculator&assumption=%7B%22F%2 …
> Rewritten list query, test and fix [#82]

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/sqllog/sql.go
- test/list_test.go
> Kv should be mkv

- .github/workflows/go.yaml
- Makefile
- hack/dynamic-go-install.sh
- hack/static-go-install.sh
Follow up fixes on #90 
- use bin/dynamic/lib for dqlite shared libraries
- configurable build-scripts directory
- use `go install` for dqlite cli tool
> Follow up fixes on k8s-dqlite build process

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/server/list.go
- pkg/kine/server/types.go
- test/list_test.go
Update k8s-dqlite to pass the Kubernetes 1.29 conformance tests
- Compaction only ignores the last 100 revisions (from 1000).
- List responses return keys in alphabetical order.
- List requests with paging now return the correct `Count` of results that remain
- List requests with paging properly handle the start key.
- Properly handle list responses where the keys revisions are not in alphabetical order.
See the individual commits for details. Each commit is accompanied by a test case that doesn't work without the introduced changes.
> 1.29 conformance fixes

- .github/workflows/go.yaml
- hack/dynamic-go-build.sh
- hack/dynamic-go-install.sh
Update build scripts for dynamically linked binaries to look for dqlite in `$PWD/lib` and `$PWD/../lib` by default.
> Use rpath for dynamically linked binaries

- pkg/kine/drivers/sqlite/sqlite_test.go
The initial schema for the migration test was missing a column and the test was failing.
> Fix migration test

- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/server/types.go
- test/compaction_test.go
This PR aims at making the `DoCompact` operation interruptible from the outside, so that it is easier to test.
> Make DoCompact operation interruptible

- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
During high contention SQLite will sometime return `SQLITE_BUSY`. In those cases, the driver should retry the query for some arbitrary number of times, before giving up, to make the query more reliable.
This PR adds both the logic for sqlite driver and the generic retry logic for `GetCompactRevision` which was missing it.
> Improve retry logic

- Makefile
- cmd/root.go
- cmd/version.go
- cmd/version_no_dqlite.go
- pkg/server/server.go
- pkg/server/server_no_dqlite.go
This PR aims at making it possible to `go build .` the project without libdqlite in the system. This is essential if we want to be able to test all project (i.e. run `go test ./...`).
> Allow builds without libdqlite

- test/create_test.go
- test/delete_test.go
- test/get_test.go
- test/lease_test.go
- test/list_test.go
- test/update_test.go
This PR aims at measuring time only for the workload of the benchmarks and ignore the setup work. This way we should get more accurate results to compare.
> Bench time workload

- test/update_test.go
This test is too imprecise to be useful and making it precise is unpractical. Right now if the second batch takes *twice* the time (leading to an exponential growth) the test still pass.
It is also the test that takes the longest amount of time in the whole pipeline.
> Remove UpdateSameKeyLinearity

- pkg/kine/broadcaster/broadcaster.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/generic_test.go
- pkg/kine/endpoint/endpoint.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/server/types.go
- pkg/server/server.go
- test/admission_test.go
- test/create_test.go
- test/delete_test.go
- test/get_test.go
- test/lease_test.go
- test/list_test.go
- test/update_test.go
- test/util_test.go
- test/util_test_dqlite.go
- test/watch_test.go
This PR adds a way for the Server to wait for other services (like the Backend, the event polling, the cleanup for ttl, the watchers, etc...) to end during shutdown.
It is useful mainly during tests/benchmarks so that we are sure that once the test is over, no service is still running.
> Add synchronization primitive for server shutdown

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Minor updates to the Readme and PR template to include Canonical Kubernetes.
> Readme & PR template

- pkg/kine/drivers/generic/admission_test.go
- test/get_test.go
- test/list_test.go
- test/update_test.go
This PR aims at reducing the boilerplate for tests and benchmarks. In that direction it:
- aligns the names of the utility function (now consistently called `{create,update,delete}Key`)
- tries to use them everywhere possible
- aligns the usage of gomega for the admission test
- removes unused helper functions
From a functionality level, it also removes same-nesting inter-test dependencies which might break the tests if the run filters them (very present in the list tests). This has also a nice effect of reducing a bit indentation.
> Simplify integration tests

- .github/workflows/go.yaml
- Makefile
This PR makes each benchmark run at least 7 times (which in general is the minimum amount of repetitions to compute `p` with `benchstat` tool).
Given that this will increase again bench time, I removed the building of dqlite and used the PPA instead, so that some of the time spent there can be saved.
> Stable benchmarks

- pkg/kine/drivers/generic_test.go
- test/util_test.go
Logrus output during tests is flooding the output and making it difficult to properly run `benchstat` on the output. This PR redirects the output to `io.Discard` for that and sets the log level to `Fatal` so that the log footprint is minimal.
> Suppress logrus output during tests

- .github/workflows/go.yaml
This PR gather results from the benchmarking job and compares them with the base branch, so that we can monitor how a change affects performance.
It mostly uses standard tooling, so the output is still a bit rough, but I think it's for the best as it's the same format one would read while running benchmarks on his own machine.
It is a duplicate of #122  but it comes from the repo itself, so it should have the right permission.
> Add continuous benchmarking

- go.mod
- go.sum
The latest stable version of `go-sqlite` is `v1.14` or later, not `v2`, as described [in the readme](https://github.com/mattn/go-sqlite3/blob/master/README.md), and AFAIK `v2` has been retired (see the `+incompatible` tag in the go mod).
This PR points `go-sqlite` dependency to `v1.14`.
> Update go-sqlite3 to the last version

- pkg/instrument/extension.c
- pkg/instrument/extension.h
- pkg/instrument/sqlite.go
- test/admission_test.go
- test/compaction_test.go
- test/create_test.go
- test/delete_test.go
- test/get_test.go
- test/lease_test.go
- test/list_test.go
- test/update_test.go
- test/util_test.go
- test/watch_test.go
This PR enables monitoring SQLite performance metrics. In detail, it adds the following metrics:
- pages written
- cache spill (when the write cache needs to be unloaded as the transaction is too big)
- pages read
- read cache hits
- time spent in a read transaction
- time spent in a write transaction
These will be useful to understand how a new query impacts the database.
> Instrument SQLite

- pkg/kine/drivers/sqlite/schema.go
- pkg/kine/drivers/sqlite/schema_test.go
- pkg/kine/drivers/sqlite/sqlite.go
Enable minor schema version updates.
> Enable minor schema version updates

- pkg/kine/logstructured/logstructured.go
At the moment `logstructured.create` is not a single transaction (which is the plan for future work).
There is a rare concurrency issue resulting as a result of a lack of error handling and a bug in the code. The quick fix here is to set the previous revision of the newly created entry to zero always as a new entry does not have a previous revision to refer to in the first place.
We can run into troubles as `rev` is not zero when passed (which leads to pointing to a wrong previous revision, it doesn't have any), and changes when another entry gets inserted in the meantime. In rare circumstances we could end up with two insert of the same key with different previous revisions.
> Address concurrency issue in logstructured.create

- test/admission_test.go
- test/compaction_test.go
- test/delete_test.go
- test/get_test.go
- test/list_test.go
- test/util_test.go
This PR fixes the list test so that it is possible to get reliable metrics from it and adds a test for pagination.
> Improve list test and resize admission test

- pkg/kine/drivers/generic/admission.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
This PR improves the create method by moving the logic into one query.
The create query:
- If there is no previous entry for a given key the query inserts the new row with the key and its value.
- If there is a previous entry for a given key exists:
-  where the previous entry is not a deleted entry, the query inserts the new row with the key and its value.
-  where the previous entry is a deleted entry, the query does nothing.
Then we check if any rows have been affected by the query, if not we return a key exists error.
Note: we will make an update to the `kine_name_index` when we update the schema version to include `delete`. This will allow us to have a covering index for the new create query.
> Improve create query

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/prepared/db.go
- pkg/kine/prepared/tx.go
- test/compaction_test.go
- test/util_test.go
This PR rewrites the compaction step in a similar way [upstream](https://github.com/k3s-io/kine/pull/51) is doing. This way, the throughput should be a lot higher. The main differences from upstream are:
- small batches instead of a single big one;
- proper range boundaries to reduce search space;
- in-transaction update of the compaction version.
This query does not use indexes right now. It's still *way faster* than what we have and what upstream has. Maybe we could improve things with a covering index if/when it's needed for the Watch/TTL query. Otherwise we might be ok with what we have.
Up to this point we've been doing compaction on each revision within the compaction range row by row. Looping over all revisions takes about 7s on an idle cluster, rare issues have been recorded where …
> Improve compaction

- hack/dynamic-dqlite.sh
- hack/static-dqlite.sh
The Juju team discovered segfault issues building dqlite on arm64 machines, this flag addresses the issues: `-Wl,-z,stack-size=1048576`
See: https://wiki.musl-libc.org/functional-differences-from-glibc.html#Thread-stack-size
> Dqlite arm64 build fix

- cmd/root.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/server/server.go
This PR adds a timeout on long running after queries which are part of the watcher's poll loop. 
The timeout is configurable using the `watch-query-timeout` flag.
This PR addresses issues raised in microk8s where after the leader node is removed from the cluster the remaining nodes also go into `NotReady` state for ~20 minutes. This timeout helps the responsiveness of the cluster after loosing its leader.
The largest part of this code change is passing the timeout arg to the poll loop.
Look at files in this order: root.go -> server.go (params encoded in driver string) -> sqlite.go (parsed, set on dialect which is generic)-> generic.go (returns timeout) -> sql.go (watcher poll loop)
> Configurable watch query timeout

- .github/workflows/go.yaml
- test/list_test.go
This PR fixes a problem in the List benchmark. It also makes sure that the CI pipeline for benchmarks fail if an error occurs (it was ignoring the error before).
> Fix list benchmark and notify CI on error

- .github/workflows/build-snap.yml
- app/app.go
- app/options/options.go
- go.mod
- go.sum
- server/server.go
Back-port watcher query timeout fix: https://github.com/canonical/k8s-dqlite/pull/162
Depends on https://github.com/canonical/kine/pull/33.
> Watcher query timeout Backport Microk8s 1.28 

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/sqllog/sql.go
`GetRevision` method (and the associated query) were used in the compaction only. Now no code calls that function.
As such, I removed it.
> Remove unused GetRevision query

- README.md
- cmd/root.go
- pkg/kine/drivers/dqlite/dqlite.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/drivers/sqlite/sqlite_test.go
- pkg/kine/endpoint/endpoint.go
- pkg/server/server.go
We use a connection pool to talk with the database. This connection pool can be configured.
Existing connections are not actively closed by us, we lazily close them via the connection pool configuration.
Through this PR we can set the connection pool configurations via flags.
This PR attempts to mitigate an issue where the leader node is killed and connections are "hanging" on the old connection of the killed node.
Sql allows us to configure these parameters:
- [SetMaxOpenConns](https://pkg.go.dev/database/sql#DB.SetMaxOpenConns)
- [SetMaxIdleConns](https://pkg.go.dev/database/sql#DB.SetMaxIdleConns)
- [SetConnMaxIdleTime](https://pkg.go.dev/database/sql#DB.SetConnMaxIdleTime)
- [SetConnMaxLifetime](https://pkg.go.dev/database/sql#DB.SetConnMaxLifetime)
We currently use:
- MaxIdleConns: 5 …
> Make connection pool configurable

- test/lease_test.go
- test/update_test.go
Note that calling lease grant doesn't do anything but return a response to k8s, leases and ttl are handled by a long running go routine in the kine layer: [pkg/kine/logstructured/logstructured.go](https://github.com/canonical/k8s-dqlite/blob/master/pkg/kine/logstructured/logstructured.go#L383).
Removing the benchmark test because it is not measuring any lease performance.
The function `updateKey` is not used and can be removed.
> Code cleanup remove lease test and dead code

- docs/versioning.md
Updating versioning docs since MK 1.28 will be pointed at v1.1.11 as well now.
> Update versioning docs

- test/create_test.go
- test/delete_test.go
- test/update_test.go
Single threading benchmarking is interesting, but it is also necessary to understand how the system behaves in the face of multiple concurrent clients contenting the database.
This PR adds concurrency to the write path, while keeping operations distinct (i.e. no mixed create/update/delete load). While still a synthetic load, it can be considered "closer to reality".
> Add concurrency to create/update/insert benchmarks

- test/admission_test.go
- test/compaction_test.go
- test/delete_test.go
- test/get_test.go
- test/list_test.go
- test/update_test.go
- test/util_test.go
The delete benchmark right now is using the path for the "[unconditional delete](https://github.com/kubernetes/kubernetes/blob/v1.14.0/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L191)" which is what k8s 1.14 and previous was using. 
Since v1.15 it is now using a [conditional delete](https://github.com/kubernetes/kubernetes/blob/v1.32.0-alpha.0/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L277) instead.
As such, that is what we should test.
> Fix delete benchmark

- pkg/kine/drivers/generic/generic.go
- pkg/kine/logstructured/sqllog/sql.go
- pkg/kine/server/watch.go
- test/watch_test.go
The current watch test has inter dependencies from subtests and as such subtests cannot be run individually, but only as a whole.
This PR attempts to overcome this issue and make them independent. 
It also fixes some checks:
- `KV.Value` in delete event should be `nil`
- `PrevKV.Key` should be correctly populated
- `[Prev]KV.CreateRevision` should be correctly populated
These new checks highlighted a small bug in the update query which should now be fixed.
> Fix watch test

- test/create_test.go
- test/delete_test.go
- test/update_test.go
This PR renames the subtests that use multiple workers so that they can be easily filtered by backend type.
As of now, doing `go test -run ^$ -branch "./dqlite" does not select those tests. This PR makes sure that they are all part of the same cathegory.
> Rename concurrent tests for create, delete and update

- README.md
- docs/configuration.md
- docs/development.md
- docs/versioning.md
This PR is adding a reference page for our k8s-dqlite arguments, a development docs page and gives a general make-over to our existing pages.
> Adding Config Reference & Development Docs plus Readme Makeover

- test/create_test.go
- test/delete_test.go
- test/update_test.go
This PR increases the number of concurrent writers in the write loads.
This is useful to showcase how processing will change once #180 is ready.
> Increase parallelism for write benchmarks

- .github/workflows/k8s-snap-integration.yaml
This PR adds a test for our newest changes of k8s-dqlite against our latest [k8s-snap](https://github.com/canonical/k8s-snap).
Through this test we can guarantee k8s features (network, ingress, gateway, storage, etc) work as expected.
> K8s-snap integration test with k8s-dqlite changes

- .github/workflows/k8s-snap-integration.yaml
- docs/development.md
Through this PR we cancel in flight integration tests that are running when newer changes are pushed.
> Cancel concurrent workflow k8s-snap integration test

- pkg/kine/drivers/sqlite/sqlite.go
- test/util_test.go
This PR changes the way sqlite is initialized, so that it is similar (in terms of guarantees) to what dqlite is doing.
As such, we want:
- WAL mode (it was journal mode before);
- synchronous=FULL (dqlite protects commits from power outages once committed)
- checked foreign_keys
This might be one of the reasons we see sometimes very different results from dqlite and sqlite.
> Fix sqlite initialization flags

- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
This logic was replaced by create, update and delete logic.
> Remove old append/insert logic

- .github/workflows/performance.yaml
- .gitignore
- test/performance/Readme.md
- test/performance/parse-performance-metrics.R
- test/performance/tests/test_multi_node.py
- test/performance/tests/test_single_node.py
- test/performance/tests/test_util/config.py
- test/performance/tests/test_util/harness/lxd.py
- test/performance/tests/test_util/metrics.py
This PR takes care of parsing the metrics from the load test (single & three-node) and uploading the results to an artifact.
(GH does not allow uploading images to GH comments- this was the original plan).
We generate the following files & directories:
| Folder | Files |
|------------| --------|
| head | head-1-three-node.log, head-2-three-node.log, head-3-three-node.log , head-1-single-node.log |
| base-code | base-code-1-three-node.log, base-code-2-three-node.log, base-code-3-three-node.log , base-code-1-single-node.log 
| v1-1-11 | ... |
| v1-2-0  | ... |
The test creates another directory for the single-node comparison:
| Folder | Files |
|------------| --------|
| single-node| head-1-single-node.log, base-code-1-single-node.log, v1-2-0 -1-single-node.log, v1-1-11-1-single-node.log| …
> Performance Test Parse Metrics (3)

- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/logstructured/logstructured.go
- pkg/kine/logstructured/sqllog/sql.go
- test/update_test.go
This PR aims to simplify the read path by:
- merging the query for `{List, Count}Current` with `{List, Count}`. The count query might have a slight increase in latency, but not important enough to care
- solving a potential (and rare) concurrency bug for the `List` query: the revision was fetched after the list, so we might have returned the wrong version for the list
- removing the logic to support mysql and postgres parameter naming
- removing the customization hooks for other dialects
> Simplify keys read path

- .github/workflows/trivy.yaml
This pr adds trivy scan for release branches
KU-2031
> Add Trivy scan for release branches

- .github/workflows/performance.yaml
- test/performance/tests/test_util/metrics.py
Removing tag comparison on the tags, this is unnecessary because we can get the comparison by changing the base-code of a PR.
> Performance test remove tag comparison

- pkg/kine/drivers/generic/generic.go
- pkg/kine/sqllog/sqllog.go
This PR takes advantage from the reduced need of SQLLog after the merge LogStructured. This should result in a smoother startup and less data passed through the network.
> Improve queries after LogStructured removal

- docs/versioning.md
This PR updates the versioning docs to include the new v1.3.0 tag.
> v1.3.0 tag versioning docs

- .github/workflows/k8s-snap-integration.yaml
- .github/workflows/performance.yaml
- pkg/kine/server/get.go
* bump Python version, k8s-snap tests now require Python 3.10
* use self-hosted jammy runner
* fix r installation
* remove broken kine check
* use composite action from k8s-snap to install LXD
> Unblock CI

- pkg/kine/drivers/dqlite/dqlite.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/server/types.go
This PR removes `TranslateErr` from `Generic` as that was a goofy way to return `ErrKeyExists` to the server.
We are now managing that by explicitly returning a bool from transactions. Also our queries do not fail any more, but they just don't insert anything (which is a requirement for batching).
> Remove TranslateErr from Generic

- test/performance/tox.ini
The CI job duration increased significantly after switching to self-hosted runners.
We'll update the pytest invocation to log timestamps, which should help us uncover potential bottlenecks.
> pytest: log timestamps

- .github/workflows/performance.yaml
- test/performance/tests/conftest.py
- test/performance/tests/test_multi_node.py
- test/performance/tests/test_single_node.py
- test/performance/tests/test_util/config.py
- test/performance/tests/test_util/harness/__init__.py
- test/performance/tests/test_util/harness/base.py
- test/performance/tests/test_util/harness/lxd.py
- test/performance/tests/test_util/metrics.py
- test/performance/tests/test_util/util.py
This PR introduces the following perf test improvements:
* make kube-burner timeout configurable (default to 10m)
* attempt to collect perf metrics even in case of test failures
* configurable dqlite trace level
* configurable k8s-dqlite log level
Those changes should allow us to determine the cause of the recent kube-burner timeouts:
```
time="2025-01-14 13:13:58" level=error msg="Error found removing Secret secret-1: rpc error: code = Unknown desc = exec (try: 500): database is locked"
time="2025-01-14 17:12:18" level=error msg="4h0m0s timeout reached"
```
> perf test improvements

- go.mod
- go.sum
This PR Addresses the following security alerts:
- https://github.com/canonical/k8s-dqlite/security/code-scanning/64
- https://github.com/canonical/k8s-dqlite/security/code-scanning/146 (Critical)
- Bump golang.org/x/net to v0.33.0
- Bump github.com/golang-jwt/jwt/v4 to v4.5.1
> deps: Address security alerts

- .github/workflows/performance.yaml
- hack/dynamic-dqlite.sh
- hack/dynamic-go-build.sh
- hack/static-dqlite.sh
- hack/static-go-build.sh
- test/performance/tests/conftest.py
- test/performance/tests/test_util/config.py
- test/performance/tests/test_util/util.py
In order to debug crash dumps such as the dqlite ones that we're experiencing, we'll make the following changes:
* include debug symbols by default
* collect core dumps
* upload the snaps in case of e2e test failures so that we may analyse the core dumps
Depends on: https://github.com/canonical/k8s-snap/pull/1014
> Collect core dumps

- .github/workflows/performance.yaml
By mistake, we're using the same name for both snap artifacts, which is why the snap upload fails.
This commit will update the artifact names to match the snap file names.
> perf test: fix snap artifact names

- .github/workflows/tiobe-tics-cron.yaml
- Makefile
Adds TICS nightly scan github action.
* add new `go.coverage` Makefile target
* add nightly workflow for running TICS scan
Based on: https://github.com/canonical/k8s-dqlite/pull/204
> ci: add Tiobe TICS nightly workflow with coverage

- pkg/server/server.go
For context see issue: https://github.com/canonical/k8s-dqlite/issues/196
The currently used Dqlite snapshot parameters are set too high for small clusters.
This PR adjusts the default snapshot parameter's used.
It also implements some guardrails for setting the parameters via the tuning config.
> Default and minimum snapshot parameters

- pkg/kine/drivers/dqlite/dqlite.go
- pkg/kine/drivers/generic/generic.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/drivers/sqlite/sqlite_test.go
- pkg/kine/endpoint/endpoint.go
- pkg/kine/sqllog/sqllog.go
- test/util_test.go
This PR moves the instantiation of `SQLLog` away from the `drivers` folder as it is not a drivers concern to decide how they should be used.
It also renames `Dialect` to `Driver` to match naming.
> refactor: return driver from drivers methods

- pkg/server/server.go
the new method preserves the role of the node from previous cluster
> chore: replace deprecatd dqlite reconfigure membership method

- cmd/root.go
- pkg/kine/drivers/dqlite/dqlite.go
- pkg/kine/drivers/sqlite/driver.go
- pkg/kine/drivers/sqlite/generic.go
- pkg/kine/drivers/sqlite/metrics.go
- pkg/kine/drivers/sqlite/sqlite.go
- pkg/kine/drivers/sqlite/sqlite_test.go
- pkg/kine/endpoint/endpoint.go
- pkg/kine/server/server.go
- pkg/server/server.go
- test/compaction_test.go
- test/create_test.go
- test/delete_test.go
- test/get_test.go
- test/lease_test.go
- test/list_test.go
- test/update_test.go
- test/util_test.go
- test/watch_test.go
This PR removes the `generic` package and merges that with `sqlite`.
It also takes this opportunity to move many driver-unrelated stuff up in the instantiation chain, so that `sqlite` is now just a driver around a `*sql.DB` connection that is able to "talk" SQLite  sql dialect.
> refactor: remove `generic` package

- pkg/kine/sqllog/sqllog.go
We've detected a leak in the watch poll loop.
The watch context never gets cancelled as it is part of the long running loop:
> bug: Fix memory leak watch context cancel

- pkg/kine/logstructured/sqllog/sql.go
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
> back-port: [v1.2] Fix memory leak watch context cancel (#240)

- .github/workflows/go.yaml
- pkg/kine/logstructured/sqllog/sql.go
Back-port of https://github.com/canonical/k8s-dqlite/pull/240
> back-port: [v1.1] Fix memory leak watch context cancel (#240)

- test/performance/tests/conftest.py
We're initiating the instance cleanup before retrieving the inspection reports.
For this reason, k8sd becomes unavailable, affecting the k8s-snap inspection report script, which will no longer be able to retrieve all logs or determine the node role.
> Collect inspection reports before deleting the instances

- .github/workflows/performance.yaml
By mistake, we're adding the test name (e.g. head, base-code) to the perf report path twice, ending up with: $reportsDir/head/head/single-node.
We'll drop the test name from the TEST_INSPECTION_REPORTS_DIR setting, letting the tests handle the subdirectories.
> Fix perf reports, unblocking the CI

- pkg/kine/drivers/sqlite/driver.go
- pkg/kine/server/create.go
- pkg/kine/server/delete.go
- pkg/kine/server/get.go
- pkg/kine/server/list.go
- pkg/kine/server/types.go
- pkg/kine/server/update.go
- pkg/kine/server/watch.go
- pkg/kine/sqllog/sqllog.go
- test/compaction_test.go
k8s-dqlite can now properly use ranges, so we no longer need to use fragile prefix logic.
Note that in order to properly support etcd range semantics, we need to change the type of the "key" and "limit" arguments to []byte. This means that we'll need to perform a cast as part of the SQL query.
For now we'll only change the List and Count methods. For consistency, we could update the other methods as well in a follow-up patch.
> Use list ranges instead of prefixes

- pkg/database/batched.go
- pkg/database/batched_test.go
- pkg/k8s_dqlite/drivers/dqlite/driver.go
- pkg/k8s_dqlite/drivers/sqlite/driver.go
- pkg/k8s_dqlite/drivers/sqlite/driver_test.go
- pkg/server/server.go
- test/util_test.go
All update operations (insert/update/delete) force a fsync on the WAL (and sometimes on the disk because of checkpoints). This limits the number of operations to what the underlying disk can do (usually in the order of hundreds).
Grouping these operations in transactions should dramatically increase the throughput while making the top X%ile latency a bit higher. However, this should be balanced by a lower latency in the bottom X%ile.
*We should test this also on a real cluster.*
This PR also removes the write lock as now there is always only one active writer.
> perf: add query batching

- test/performance/templates/api-intensive.yaml
This PR aims at reducing the amount of time taken by the benchmarking job.
If I read the logs correctly, each run (base, head) takes 15 iterations which add up to 60 total iterations:
- 15 for the 1-node base
- 15 for the 3-node base
- 15 for the 1-node head
- 15 for the 3-node head
Each job waits 1 minute by default before starting. This means that an hour is wasted just waiting for the benchmark to start.
> workflows: remove wait time from perfromance test

- test/performance/tests/conftest.py
We can save a significant amount of time by initializing harness instancess and collecting inspection reports in parallel.
For 3-node tests, this reduces the init + cleanup duration from 101.83s to 55.62s.
> CI: Initialize harness instances in parallel

- .github/workflows/k8s-snap-integration.yaml
In order to catch regressions and flakes in a timely manner, we'll run all k8s-snap e2e tests (tox -e integration -- --tags up_to_weekly).
Implements: KU-2799
> CI: run all k8s-snap tests

- .github/workflows/performance.yaml
We'll cache the R libraries (/usr/local/lib/R/site-library/) using actions/cache to avoid rebuilding every time, saving a few minutes per run.
We'll also install ``r-base`` using ``--no-install-recommends`` to avoid unnecessary packages.
> CI: cache R dependencies

- .github/workflows/k8s-snap-integration.yaml
We'll run the CNCF tests along with the other k8s-snap e2e tests nightly or whenever the PRs have the "cncf-conformance" label.
Based on the following PRs:
* https://github.com/canonical/k8s-snap/pull/1125
* https://github.com/canonical/k8s-dqlite/pull/198/
> CI: run CNCF tests nightly or when requested through labels

- .github/actions/patch-k8s-snap/action.yaml
- .github/workflows/k8s-snap-integration.yaml
- .github/workflows/performance.yaml
We have two jobs that perform the following steps:
* build k8s-dqlite
* download k8s-snap
* unsquash the snap
* patch k8s-dqlite
* recreate the snap file
To simplify the workflows and avoid redundant logic, we'll define a reusable action.
> CI: use a composite action for rebuilding the snap

- cmd/root.go
- docs/configuration.md
- docs/development.md
- pkg/server/server.go
This PR adds logging for the go-dqlite driver.
Also adds log-levels that can be set through the root command options. Depreciates --debug flag.
Example:
```
ubuntu@louise-dev2:~/k8s-dqlite$ sudo ./bin/static/k8s-dqlite     --storage-dir /var/snap/k8s/common/var/lib/k8s-dqlite     --listen unix:///var/snap/k8s/common/var/lib/k8s-dqlite/k8s-dqlite.sock --log-level=debug
INFO[0000] configure dqlite failure domain               failure-domain=0
INFO[0000] disable TLS ClientSessionCache               
INFO[0000] enable TLS                                    min_tls_version=tls12
INFO[0000] configure dqlite raft snapshot parameters     threshold=512 trailing=4096
DEBU[0000] [go-dqlite] new connection from 192.168.105.17:50638 
DEBU[0000] [go-dqlite] attempt 1: server 192.168.105.17:9000: …
```
> feat: add logging for go-dqlite driver

- go.mod
- pkg/kine/logstructured/logstructured.go
We have a bug where essentially if the lease deletion fails on all nodes of the cluster the deletion is not retried unless the k8s-dqlite service is restarted in which case the lease removal and its timer are restarted.
This patch introduces an unlimited retry back-off for the lease deletion.
Backport of https://github.com/canonical/k8s-dqlite/pull/298
> [backport v1.3] fix: never drop lease deletion

- test/lease_test.go
The lease unit test creates a key with one second TTL and then waits two seconds for the key to be removed before timing out. Since there is a [random jitter](https://github.com/canonical/k8s-dqlite/blob/fbab30e641aab2e0e9018505ea658fe50f90b868/pkg/backend/internal/backend/ttl.go#L90-L92) with sets at most one second gap between expiry of the key and removing it, the jitter may cause the test to timeout and introduce a flakiness. This PR adds another 100ms to the test timeout to avoid such possibility.
> fix: lease test flakiness

- hack/dynamic-go-build.sh
- hack/dynamic-go-install.sh
This PR backports https://github.com/canonical/k8s-dqlite/pull/316 that enables passing Go build tags.
> chore: [Backport 1.7] Pass Go tags using environment variables (#316)

- test/performance/templates/api-intensive.yaml
(cherry picked from commit f88169313c034bd94bb056960e6b6f91c4e473ee)
This PR aims at reducing the amount of time taken by the benchmarking job.
If I read the logs correctly, each run (base, head) takes 15 iterations which add up to 60 total iterations:
- 15 for the 1-node base
- 15 for the 3-node base
- 15 for the 1-node head
- 15 for the 3-node head
Each job waits 1 minute by default before starting. This means that an hour is wasted just waiting for the benchmark to start.
> workflows: remove wait time from performance test (#252)
